# Generated by Django 4.2.6 on 2023-10-31 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('kcal', models.FloatField(default=0)),
                ('grasas', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('duracion', models.IntegerField()),
                ('ingredientes', models.ManyToManyField(to='appEmpresaRecetas.ingrediente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEmpresaRecetas.tipoplato')),
            ],
        ),
    ]
