# Generated by Django 4.2.6 on 2023-11-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresaRecetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='nombre',
            field=models.CharField(max_length=70),
        ),
    ]
