# Generated by Django 4.2.6 on 2023-11-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresaRecetas', '0002_receta_imagen_alter_receta_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de publicación')),
                ('pregunta', models.CharField(max_length=200)),
            ],
        ),
    ]
