# Generated by Django 4.2.6 on 2023-11-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresaRecetas', '0008_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
