# Generated by Django 4.2.6 on 2023-11-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresaRecetas', '0010_remove_pregunta_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='tiempo',
            field=models.IntegerField(default=0),
        ),
    ]
