# Generated by Django 4.2.6 on 2023-11-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresaRecetas', '0011_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('comentario', models.CharField(max_length=500)),
            ],
        ),
    ]
