# Generated by Django 4.2.6 on 2023-12-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresaRecetas', '0012_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='accept',
        ),
    ]
