# Generated by Django 4.2.6 on 2023-12-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresaRecetas', '0013_remove_pregunta_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
